version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: app
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
